FROM docker.io/python:3.11-slim

COPY requirements.txt /requirements.txt
COPY requirements.dev.txt /requirements.dev.txt
COPY requirements.ci.txt /requirements.ci.txt

RUN pip install \
	-r requirements.txt \
	-r requirements.ci.txt \
	-r requirements.dev.txt

COPY . /bot
