FROM docker.io/python:3.11-slim

COPY requirements.txt /bot/requirements.txt
COPY requirements.dev.txt /bot/requirements.dev.txt

RUN pip install \
	-r /bot/requirements.txt \
	-r /bot/requirements.dev.txt
