version: "3"
services:
  bot:
    volumes:
      - .:/bot
      - "${BOT_CERT_DIR}:/botcert:ro"
    user: "${CONTAINER_UID}:${CONTAINER_UID}"
  celery-worker:
    volumes:
      - .:/bot
    user: "${CONTAINER_UID}:${CONTAINER_UID}"
  celery-beat:
    volumes:
      - .:/bot
    user: "${CONTAINER_UID}:${CONTAINER_UID}"
  rabbitmq:
    volumes:
      - rabbitmq-data-dev:/var/lib/rabbitmq
  redis:
    volumes:
      - redis-data-dev:/data
volumes:
  rabbitmq-data-dev: 
  redis-data-dev:
