version: "3"
services:
  bot:
    image: localhost/fjfnaranjo-bot:latest
    volumes:
      - bot-data:/bot/botdata
    command: uvicorn fjfnaranjobot.server:application
  celery-worker:
    image: localhost/fjfnaranjo-bot:latest
    volumes:
      - bot-data:/bot/botdata
    command: celery -A fjfnaranjobot.tasks worker --loglevel=info
  celery-beat:
    image: localhost/fjfnaranjo-bot:latest
    volumes:
      - bot-data:/bot/botdata
    command: celery -A fjfnaranjobot.tasks beat --loglevel=info -s /bot/botdata/celerybeat-schedule --pidfile=/bot/botdata/celerybeat.pid
  redis:
    volumes:
      - redis-data:/data
volumes:
  bot-data:
  redis-data:
