name: fjfnaranjo-bot
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.5
    - name: Install system dependencies
      uses: ryankurte/action-apt@v0.1.0
      with:
        packages: "libev-dev"
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements.ci.txt ]; then pip install -r requirements.ci.txt; fi
    - name: Check styles with Black
      run: black -S --check fjfnaranjobot tests
    - name: Check imports with isort
      run: isort -c
    - name: Test with pytest
      run: pytest
      env:
        BOT_OWNER_ID: 11
        BOT_TOKEN: '123456:btbtbt'
