name: fjfnaranjo-bot
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements.ci.txt ]; then pip install -r requirements.ci.txt; fi
    - name: Check styles with Black
      run: black --check fjfnaranjobot tests
    - name: Check imports with isort
      run: isort -c fjfnaranjobot tests
    - name: Test with pytest
      run: pytest tests/
      env:
        BOT_TOKEN: '123456:btbtbt'
