name: fjfnaranjo-bot
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements.dev.txt ]; then pip install -r requirements.ci.txt; fi
    - name: Check styles with Black
      run: black -S --check fjfnaranjobot tests
    - name: Check imports with isort
      run: isort -c
    - name: Test with pytest
      run: pytest
      env:
        BOT_DATA_DIR: botdata-dev
        BOT_DB_NAME: bot.test.db
        BOT_LOGFILE: bot.pytest.log
        BOT_OWNER_ID: 11
